export const categories = [
  {
    id: "#2",
    name: "Ramen",
    description: "The Description",
    goodFor: "Breakfast",
    image: require("../assets/second.jpg"),
  },
  {
    id: "#3",
    name: "Burger",
    description: "The Description",
    goodFor: "Wifi",
    image: require("../assets/third.jpg"),
  },
  {
    id: "#1",
    name: "Sushi",
    description: "The Description",
    goodFor: "Lunch",
    image: require("../assets/first.jpg"),
  },
  {
    id: "#4",
    name: "Chinese",
    description: "The Description",
    goodFor: "Out-Door Sitting",
    image: require("../assets/fourth.jpg"),
  },
  {
    id: "#5",
    name: "Ramen",
    description: "The Description",
    goodFor: "Breakfast",
    image: require("../assets/fifth.jpg"),
  },
  {
    id: "#6",
    name: "Burger",
    description: "The Description",
    goodFor: "Wi-fi",
    image: require("../assets/sixth.jpg"),
  },
];

export const foods = [
  {
    id: "$#1",
    name: "Shawama",
    category: "Burger",
    price: "$$$",
    restuarant: "Gamine",
    rating: "****",
    image: require("../assets/fifth.jpg"),
    ingredients: ["Egg", "Tomato", "Onion", "Carrot"],
    goodFor: ["Breakfast", "Wifi", "Out Door Sitting", "Lunch"],
  },
  {
    id: "$#2",
    name: "Egwusi & Amala",
    category: "Swallow",
    price: "$$$",
    restuarant: "Mama Iyabo",
    rating: "****",
    image: require("../assets/fourth.jpg"),
    ingredients: ["Egwusi", "Meat", "Onion", "Pepper"],
    goodFor: ["Breakfast", "Free Wifi", "Lunch", "Dinner"],
  },
  {
    id: "$#3",
    name: "Fried Rice",
    category: "BreakFast",
    price: "$$$",
    restuarant: "Bouche",
    rating: "****",
    image: require("../assets/third.jpg"),
    ingredients: ["Rice", "Tomato", "Onion", "Carrot"],
    goodFor: ["Breakfast", "Wifi", "Out Door Sitting", "Lunch"],
  },
  {
    id: "$#4",
    name: "Jellof Rice",
    category: "Lunch",
    price: "$$$",
    restuarant: "Chicken Republic",
    rating: "***",
    image: require("../assets/first.jpg"),
    ingredients: ["Rice", "Tomato", "Onion", "Carrot", "Chicken"],
    goodFor: ["Breakfast", "Wifi", "Out Door Sitting", "Lunch"],
  },
  {
    id: "$#5",
    name: "Pizza",
    category: "Lunch",
    price: "$$$",
    restuarant: "Humbmart",
    rating: "****",
    image: require("../assets/second.jpg"),
    ingredients: ["Egg", "Floor", "Tomato", "Onion", "Carrot"],
    goodFor: ["Breakfast", "Wifi", "Out Door Sitting", "Lunch"],
  },
];
